import { FormArray, FormControl } from "@angular/forms";

export interface Obra {
    id?: number,
    autoria: number,
    escritorio: string,
    nomeOficial: string,
    nomeAlternativo: string,
    tipoEndereco: string,
    enderecoTitulo: string,
    logradouro: string,
    numero: number,
    complemento: string,
    cep: string,
    municipio: string,
    anoProjeto: number,
    anoConstrucao: number,
    construtora: number,
    condephaat: string,
    conpresp: string,
    iphan: string,
    usoOriginal: string,
    codigoOriginal: string,
    usoAtual: string,
    codigoAtual: string,
    dataUsoAtual: number,
    status: string,
    anoDemolicao: number,
    anoRestauro: number,
    anoReforma: number,
    arquitetoReforma: number,
    latitude: number,
    longitude: number,
    referencias: string[],
    validadoProfessora: boolean,
    validadoDPH: boolean  
}
